services:
  database:
    image: postgres:17.5
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5434:5432

volumes:
  postgres_data:
